name: Deploy Docusaurus with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build \
          --build-arg POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }} \
          --build-arg GISCUS_REPO_ID=${{ secrets.GISCUS_REPO_ID }} \
          --build-arg GISCUS_CATEGORY_ID=${{ secrets.GISCUS_CATEGORY_ID }} \
          --build-arg ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} \
          --build-arg ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }} \
          --build-arg ALGOLIA_INDEX_NAME=${{ secrets.ALGOLIA_INDEX_NAME }} \
          -t docusaurus-image .

    - name: Save Docker image to file
      run: |
        docker save docusaurus-image -o docusaurus-image.tar

    - name: Copy Docker image to remote server
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$DEPLOY_KEY" | tr -d '\r' > deploy_key
        chmod 600 deploy_key
        scp -i deploy_key -o StrictHostKeyChecking=no docusaurus-image.tar ubuntu@117.50.181.177:~/github-cicd/
        rm -f deploy_key

    - name: Load and Run Docker image on remote server
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i deploy_key -o StrictHostKeyChecking=no ubuntu@117.50.181.177 << 'ENDSSH'
        docker load -i ~/github-cicd/docusaurus-image.tar
        docker run -d -p 3000:3000 docusaurus-image
        ENDSSH
